# Generated by Django 6.0.3 on 2026-05-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='images/ape1.jpg', null=True, upload_to='avatars/'),
        ),
    ]
