# Generated by Django 6.0.3 on 2026-05-05 00:38

import a_rtchat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0004_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=a_rtchat.models.generate_group_name, max_length=128, unique=True),
        ),
    ]
